from pydantic import BaseModel, Field
from typing import List

class AgentState(BaseModel):
    """
    JSON Schema to represent the state of the agent. The JSON will contain the information required for the present task and will be 
    updated at each phase of the orchestration process.
    The schema includes:
    - topic: the topic of the article to be written, provided by the user as input.
    - title: the title of the article, generated by the agent based on the topic.
    - keywords: a list of keywords to be included in the article, generated by the agent based on the topic.
    - meta_description: a meta description for the article, generated by the agent.
    - content: the main content of the article, generated by the agent.
    - wp_ready: a boolean flag indicating whether the content is ready to be published on WordPress, set to true when the content is 
                finalized and formatted for WordPress.
    """

    # Input dell'utente
    topic: str = Field(description = "Il topic dell'articolo da scrivere, fornito dall'utente come input.")

    # Variabili da aggiornare durante il processo
    title: str = Field(default = "", description = "Il titolo dell'articolo.")
    keywords: List[str] = Field(default = [], description = "Una lista di parole chiave da includere nell'articolo.")
    meta_description: str = Field(default = "", description = "Una meta description per l'articolo che sia accattivante e informativa sul contenuto in massimo 155 caratteri.")
    content: str = Field(default = "", description = "Il contenuto principale dell'articolo in formato Markdown.")
    wp_ready: bool = Field(default = False, description = "Un flag booleano che indica se il contenuto è pronto per essere pubblicato su WordPress.")

class ValidityCheckState(BaseModel):
    """
    JSON Schema to represent the state of the validity check for the topic provided by the user. This schema will be used to determine if the topic is valid and if it makes sense to write an article about it.
    The schema includes:
    - keywords: a list of keywords related to the topic, generated by the agent if the topic is deemed valid.
    - is_valid: a boolean flag indicating whether the topic is valid or not, set to true if the topic is valid and makes sense for an article.
    - reason: a string providing a brief explanation of why the topic is not valid , especially in cases where the topic is deemed invalid.
    """
    keywords: List[str] = Field(default = [], description = "Una lista di parole chiave correlate al topic.")
    is_valid: bool = Field(default = False, description = "Un flag booleano che indica se il topic è valido o meno.")
    reason: str = Field(default = "", description = "Una stringa che fornisce una breve spiegazione del motivo per cui il topic è valido o meno.")

class WordPressMetadata(BaseModel):
    title: str = Field(description="Il titolo dell'articolo, estratto dal primo H1 (#).")
    meta_description: str = Field(description="Meta description SEO accattivante, max 155 caratteri.")

class Outline(BaseModel):
    outline: List[str] = Field([], description= "Una lista di stringhe che rappresentano i titoli dei paragrafi dell'articolo.")
    copywriter_directives: List[str] = Field([], description = "Una lista di stringhe che rappresenta le direttive che il copywriter deve seguire per introdurre ogni keyword.")
